# Generated by Django 3.0.7 on 2020-07-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='badge',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'success'), ('D', 'dark'), ('W', 'warning')], max_length=1),
        ),
    ]
