# Generated by Django 3.0.8 on 2020-07-10 00:49

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200704_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=martor.models.MartorField(),
        ),
    ]
